name: bmi_calculator
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"
<<<<<<< HEAD
dependencies:
  flutter:
    sdk: flutter

=======


dependencies:
  flutter:
    sdk: flutter
>>>>>>> 0aec932b51a85e9dbf49f148b100555ae49867a6
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

<<<<<<< HEAD
  
  flutter_lints: ^1.0.0



=======
  flutter_lints: ^1.0.0

>>>>>>> 0aec932b51a85e9dbf49f148b100555ae49867a6
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

<<<<<<< HEAD


=======
>>>>>>> 0aec932b51a85e9dbf49f148b100555ae49867a6
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
<<<<<<< HEAD
  
=======
  
>>>>>>> 0aec932b51a85e9dbf49f148b100555ae49867a6
